-- =============================================
-- ElAdmin 系统 PostgreSQL code模式 初始化脚本
-- 兼容 PostgreSQL 17+
-- 生成时间：2026-01-31
-- =============================================

begin;

-- drop schema if exists code;
create schema code;

-- code.td_column
-- drop table if exists code.td_column;
CREATE TABLE code.td_column
(
    column_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name      VARCHAR(180),
    column_name     VARCHAR(255),
    column_type     VARCHAR(255),
    dict_name       VARCHAR(255),
    extra           VARCHAR(255),
    form_show       BOOLEAN,
    form_type       VARCHAR(255),
    key_type        VARCHAR(255),
    list_show       BOOLEAN,
    not_null        BOOLEAN,
    query_type      VARCHAR(255),
    remark          VARCHAR(255),
    date_annotation VARCHAR(255)
);
CREATE INDEX idx_code_column_table_name ON code.td_column (table_name);
COMMENT
    ON TABLE code.td_column IS '代码生成字段信息存储';
COMMENT
    ON COLUMN code.td_column.column_id IS 'ID';
COMMENT
    ON COLUMN code.td_column.table_name IS '表名';
COMMENT
    ON COLUMN code.td_column.column_name IS '数据库字段名称';
COMMENT
    ON COLUMN code.td_column.column_type IS '字段类型';
COMMENT
    ON COLUMN code.td_column.dict_name IS '字典名称';
COMMENT
    ON COLUMN code.td_column.extra IS '额外信息';
COMMENT
    ON COLUMN code.td_column.form_show IS '表单显示';
COMMENT
    ON COLUMN code.td_column.form_type IS '表单类型';
COMMENT
    ON COLUMN code.td_column.key_type IS '主外键';
COMMENT
    ON COLUMN code.td_column.list_show IS '列表显示';
COMMENT
    ON COLUMN code.td_column.not_null IS '是否非空';
COMMENT
    ON COLUMN code.td_column.query_type IS '查询方式';
COMMENT
    ON COLUMN code.td_column.remark IS '备注';
COMMENT
    ON COLUMN code.td_column.date_annotation IS '日期注解';

-- code.td_config
-- drop table if exists code.td_config;
CREATE TABLE code.td_config
(
    config_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name  VARCHAR(255),
    author      VARCHAR(255),
    cover       BOOLEAN,
    module_name VARCHAR(255),
    pack        VARCHAR(255),
    path        VARCHAR(255),
    api_path    VARCHAR(255),
    prefix      VARCHAR(255),
    api_alias   VARCHAR(255)
);
CREATE INDEX idx_code_config_table_name ON code.td_config (table_name);
COMMENT
    ON TABLE code.td_config IS '代码生成器配置';
COMMENT
    ON COLUMN code.td_config.config_id IS 'ID';
COMMENT
    ON COLUMN code.td_config.table_name IS '表名';
COMMENT
    ON COLUMN code.td_config.author IS '作者';
COMMENT
    ON COLUMN code.td_config.cover IS '是否覆盖';
COMMENT
    ON COLUMN code.td_config.module_name IS '模块名称';
COMMENT
    ON COLUMN code.td_config.pack IS '至于哪个包下';
COMMENT
    ON COLUMN code.td_config.path IS '前端路径';
COMMENT
    ON COLUMN code.td_config.api_path IS 'api路径';
COMMENT
    ON COLUMN code.td_config.prefix IS '前缀';
COMMENT
    ON COLUMN code.td_config.api_alias IS '接口别名';

-- ========================
-- 插入初始数据
-- ========================

commit;