-- =============================================
-- ElAdmin 系统 PostgreSQL mnt模式 初始化脚本
-- 兼容 PostgreSQL 17+
-- 生成时间：2026-01-31
-- =============================================

begin;

-- drop schema if exists mnt;
create schema mnt;

-- mnt.td_app
-- drop table if exists mnt.td_app;
CREATE TABLE mnt.td_app
(
    app_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255),
    upload_path   VARCHAR(255),
    deploy_path   VARCHAR(255),
    backup_path   VARCHAR(255),
    port          INTEGER,
    start_script  TEXT,
    deploy_script TEXT,
    create_by     VARCHAR(255),
    update_by     VARCHAR(255),
    create_time   TIMESTAMP,
    update_time   TIMESTAMP
);
COMMENT
    ON TABLE mnt.td_app IS '应用管理';
COMMENT
    ON COLUMN mnt.td_app.app_id IS 'ID';
COMMENT
    ON COLUMN mnt.td_app.name IS '应用名称';
COMMENT
    ON COLUMN mnt.td_app.upload_path IS '上传目录';
COMMENT
    ON COLUMN mnt.td_app.deploy_path IS '部署路径';
COMMENT
    ON COLUMN mnt.td_app.backup_path IS '备份路径';
COMMENT
    ON COLUMN mnt.td_app.port IS '端口';
COMMENT
    ON COLUMN mnt.td_app.start_script IS '启动脚本';
COMMENT
    ON COLUMN mnt.td_app.deploy_script IS '部署脚本';
COMMENT
    ON COLUMN mnt.td_app.create_by IS '创建者';
COMMENT
    ON COLUMN mnt.td_app.update_by IS '更新者';
COMMENT
    ON COLUMN mnt.td_app.create_time IS '创建日期';
COMMENT
    ON COLUMN mnt.td_app.update_time IS '更新时间';

-- mnt.td_database
-- drop table if exists mnt.td_database;
CREATE TABLE mnt.td_database
(
    db_id       VARCHAR(50) PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    jdbc_url    VARCHAR(255) NOT NULL,
    user_name   VARCHAR(255) NOT NULL,
    pwd         VARCHAR(255) NOT NULL,
    create_by   VARCHAR(255),
    update_by   VARCHAR(255),
    create_time TIMESTAMP,
    update_time TIMESTAMP
);
COMMENT
    ON TABLE mnt.td_database IS '数据库管理';
COMMENT
    ON COLUMN mnt.td_database.db_id IS 'ID';
COMMENT
    ON COLUMN mnt.td_database.name IS '名称';
COMMENT
    ON COLUMN mnt.td_database.jdbc_url IS '连接地址';
COMMENT
    ON COLUMN mnt.td_database.user_name IS '用户名';
COMMENT
    ON COLUMN mnt.td_database.pwd IS '密码';
COMMENT
    ON COLUMN mnt.td_database.create_by IS '创建者';
COMMENT
    ON COLUMN mnt.td_database.update_by IS '更新者';
COMMENT
    ON COLUMN mnt.td_database.create_time IS '创建日期';
COMMENT
    ON COLUMN mnt.td_database.update_time IS '更新时间';

-- mnt.td_deploy
-- drop table if exists mnt.td_deploy;
CREATE TABLE mnt.td_deploy
(
    deploy_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id      BIGINT,
    create_by   VARCHAR(255),
    update_by   VARCHAR(255),
    create_time TIMESTAMP,
    update_time TIMESTAMP
);
CREATE INDEX idx_mnt_deploy_app_id ON mnt.td_deploy (app_id);
COMMENT
    ON TABLE mnt.td_deploy IS '部署管理';
COMMENT
    ON COLUMN mnt.td_deploy.deploy_id IS 'ID';
COMMENT
    ON COLUMN mnt.td_deploy.app_id IS '应用编号';
COMMENT
    ON COLUMN mnt.td_deploy.create_by IS '创建者';
COMMENT
    ON COLUMN mnt.td_deploy.update_by IS '更新者';
COMMENT
    ON COLUMN mnt.td_deploy.create_time IS '创建日期';
COMMENT
    ON COLUMN mnt.td_deploy.update_time IS '更新时间';

-- mnt.td_deploy_history
-- drop table if exists mnt.td_deploy_history;
CREATE TABLE mnt.td_deploy_history
(
    history_id  VARCHAR(50) PRIMARY KEY,
    app_name    VARCHAR(255) NOT NULL,
    deploy_date TIMESTAMP    NOT NULL,
    deploy_user VARCHAR(50)  NOT NULL,
    ip          VARCHAR(20)  NOT NULL,
    deploy_id   BIGINT
);
COMMENT
    ON TABLE mnt.td_deploy_history IS '部署历史管理';
COMMENT
    ON COLUMN mnt.td_deploy_history.history_id IS 'ID';
COMMENT
    ON COLUMN mnt.td_deploy_history.app_name IS '应用名称';
COMMENT
    ON COLUMN mnt.td_deploy_history.deploy_date IS '部署日期';
COMMENT
    ON COLUMN mnt.td_deploy_history.deploy_user IS '部署用户';
COMMENT
    ON COLUMN mnt.td_deploy_history.ip IS 'IP';
COMMENT
    ON COLUMN mnt.td_deploy_history.deploy_id IS '部署编号';

-- mnt.td_deploy_server
-- drop table if exists mnt.td_deploy_server;
CREATE TABLE mnt.td_deploy_server
(
    deploy_id BIGINT NOT NULL,
    server_id BIGINT NOT NULL,
    PRIMARY KEY (deploy_id, server_id)
);
CREATE INDEX idx_mnt_deploy_server_deploy_id ON mnt.td_deploy_server (deploy_id);
CREATE INDEX idx_mnt_deploy_server_server_id ON mnt.td_deploy_server (server_id);
COMMENT
    ON TABLE mnt.td_deploy_server IS '应用与服务器关联';
COMMENT
    ON COLUMN mnt.td_deploy_server.deploy_id IS '部署编号';
COMMENT
    ON COLUMN mnt.td_deploy_server.server_id IS '服务器ID';

-- mnt.td_server
CREATE TABLE mnt.td_server
(
    server_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account     VARCHAR(50),
    ip          VARCHAR(20),
    name        VARCHAR(100),
    password    VARCHAR(100),
    port        INTEGER,
    create_by   VARCHAR(255),
    update_by   VARCHAR(255),
    create_time TIMESTAMP,
    update_time TIMESTAMP
);
CREATE INDEX idx_mnt_server_ip ON mnt.td_server (ip);
COMMENT
    ON TABLE mnt.td_server IS '服务器管理';
COMMENT
    ON COLUMN mnt.td_server.server_id IS 'ID';
COMMENT
    ON COLUMN mnt.td_server.account IS '账户';
COMMENT
    ON COLUMN mnt.td_server.ip IS 'IP';
COMMENT
    ON COLUMN mnt.td_server.name IS '名称';
COMMENT
    ON COLUMN mnt.td_server.password IS '密码';
COMMENT
    ON COLUMN mnt.td_server.port IS '端口';
COMMENT
    ON COLUMN mnt.td_server.create_by IS '创建者';
COMMENT
    ON COLUMN mnt.td_server.update_by IS '更新者';
COMMENT
    ON COLUMN mnt.td_server.create_time IS '创建日期';
COMMENT
    ON COLUMN mnt.td_server.update_time IS '更新时间';

COMMIT;