-- =============================================
-- ElAdmin 系统 PostgreSQL sys模式 初始化脚本
-- 兼容 PostgreSQL 17+
-- 生成时间：2026-01-31
-- =============================================

begin;

-- drop schema if exists sys;
create schema sys;

-- sys.td_dept
-- drop table if exists sys.td_dept;
CREATE TABLE sys.td_dept
(
    dept_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid         BIGINT,
    sub_count   INTEGER DEFAULT 0,
    name        VARCHAR(255) NOT NULL,
    dept_sort   INTEGER DEFAULT 999,
    enabled     BOOLEAN      NOT NULL,
    create_by   VARCHAR(255),
    update_by   VARCHAR(255),
    create_time TIMESTAMP,
    update_time TIMESTAMP
);
CREATE INDEX idx_sys_dept_pid ON sys.td_dept (pid);
CREATE INDEX idx_sys_dept_enabled ON sys.td_dept (enabled);
COMMENT
    ON TABLE sys.td_dept IS '部门';
COMMENT
    ON COLUMN sys.td_dept.dept_id IS 'ID';
COMMENT
    ON COLUMN sys.td_dept.pid IS '上级部门';
COMMENT
    ON COLUMN sys.td_dept.sub_count IS '子部门数目';
COMMENT
    ON COLUMN sys.td_dept.name IS '名称';
COMMENT
    ON COLUMN sys.td_dept.dept_sort IS '排序';
COMMENT
    ON COLUMN sys.td_dept.enabled IS '状态：1启用、0禁用';
COMMENT
    ON COLUMN sys.td_dept.create_by IS '创建者';
COMMENT
    ON COLUMN sys.td_dept.update_by IS '更新者';
COMMENT
    ON COLUMN sys.td_dept.create_time IS '创建日期';
COMMENT
    ON COLUMN sys.td_dept.update_time IS '更新时间';

-- sys.td_dict
-- drop table if exists sys.td_dict;
CREATE TABLE sys.td_dict
(
    dict_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    create_by   VARCHAR(255),
    update_by   VARCHAR(255),
    create_time TIMESTAMP,
    update_time TIMESTAMP
);
COMMENT
    ON TABLE sys.td_dict IS '数据字典';
COMMENT
    ON COLUMN sys.td_dict.dict_id IS 'ID';
COMMENT
    ON COLUMN sys.td_dict.name IS '字典名称';
COMMENT
    ON COLUMN sys.td_dict.description IS '描述';
COMMENT
    ON COLUMN sys.td_dict.create_by IS '创建者';
COMMENT
    ON COLUMN sys.td_dict.update_by IS '更新者';
COMMENT
    ON COLUMN sys.td_dict.create_time IS '创建日期';
COMMENT
    ON COLUMN sys.td_dict.update_time IS '更新时间';

-- sys.td_dict_detail
-- drop table if exists sys.td_dict_detail;
CREATE TABLE sys.td_dict_detail
(
    detail_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dict_id     BIGINT,
    label       VARCHAR(255) NOT NULL,
    value       VARCHAR(255) NOT NULL,
    dict_sort   INTEGER,
    create_by   VARCHAR(255),
    update_by   VARCHAR(255),
    create_time TIMESTAMP,
    update_time TIMESTAMP
);
CREATE INDEX idx_sys_dict_detail_dict_id ON sys.td_dict_detail (dict_id);
COMMENT
    ON TABLE sys.td_dict_detail IS '数据字典详情';
COMMENT
    ON COLUMN sys.td_dict_detail.detail_id IS 'ID';
COMMENT
    ON COLUMN sys.td_dict_detail.dict_id IS '字典id';
COMMENT
    ON COLUMN sys.td_dict_detail.label IS '字典标签';
COMMENT
    ON COLUMN sys.td_dict_detail.value IS '字典值';
COMMENT
    ON COLUMN sys.td_dict_detail.dict_sort IS '排序';
COMMENT
    ON COLUMN sys.td_dict_detail.create_by IS '创建者';
COMMENT
    ON COLUMN sys.td_dict_detail.update_by IS '更新者';
COMMENT
    ON COLUMN sys.td_dict_detail.create_time IS '创建日期';
COMMENT
    ON COLUMN sys.td_dict_detail.update_time IS '更新时间';

-- sys.td_job
-- drop table if exists sys.td_job;
CREATE TABLE sys.td_job
(
    job_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(180) NOT NULL,
    enabled     BOOLEAN      NOT NULL,
    job_sort    INTEGER,
    create_by   VARCHAR(255),
    update_by   VARCHAR(255),
    create_time TIMESTAMP,
    update_time TIMESTAMP,
    UNIQUE (name)
);
CREATE INDEX idx_sys_job_enabled ON sys.td_job (enabled);
COMMENT
    ON TABLE sys.td_job IS '岗位';
COMMENT
    ON COLUMN sys.td_job.job_id IS 'ID';
COMMENT
    ON COLUMN sys.td_job.name IS '岗位名称';
COMMENT
    ON COLUMN sys.td_job.enabled IS '岗位状态';
COMMENT
    ON COLUMN sys.td_job.job_sort IS '排序';
COMMENT
    ON COLUMN sys.td_job.create_by IS '创建者';
COMMENT
    ON COLUMN sys.td_job.update_by IS '更新者';
COMMENT
    ON COLUMN sys.td_job.create_time IS '创建日期';
COMMENT
    ON COLUMN sys.td_job.update_time IS '更新时间';

-- sys.td_menu
-- drop table if exists sys.td_menu;
CREATE TABLE sys.td_menu
(
    menu_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid         BIGINT,
    sub_count   INTEGER DEFAULT 0,
    type        INTEGER,
    title       VARCHAR(100),
    name        VARCHAR(100),
    component   VARCHAR(255),
    menu_sort   INTEGER,
    icon        VARCHAR(255),
    path        VARCHAR(255),
    i_frame     BOOLEAN,
    cache       BOOLEAN DEFAULT FALSE,
    hidden      BOOLEAN DEFAULT FALSE,
    permission  VARCHAR(255),
    create_by   VARCHAR(255),
    update_by   VARCHAR(255),
    create_time TIMESTAMP,
    update_time TIMESTAMP,
    UNIQUE (name),
    UNIQUE (title)
);
CREATE INDEX idx_sys_menu_pid ON sys.td_menu (pid);
COMMENT
    ON TABLE sys.td_menu IS '系统菜单';
COMMENT
    ON COLUMN sys.td_menu.menu_id IS 'ID';
COMMENT
    ON COLUMN sys.td_menu.pid IS '上级菜单ID';
COMMENT
    ON COLUMN sys.td_menu.sub_count IS '子菜单数';
COMMENT
    ON COLUMN sys.td_menu.type IS '菜单类型';
COMMENT
    ON COLUMN sys.td_menu.title IS '菜单标题';
COMMENT
    ON COLUMN sys.td_menu.name IS '组件名称';
COMMENT
    ON COLUMN sys.td_menu.component IS '组件';
COMMENT
    ON COLUMN sys.td_menu.menu_sort IS '排序';
COMMENT
    ON COLUMN sys.td_menu.icon IS '图标';
COMMENT
    ON COLUMN sys.td_menu.path IS '链接地址';
COMMENT
    ON COLUMN sys.td_menu.i_frame IS '是否外链';
COMMENT
    ON COLUMN sys.td_menu.cache IS '缓存';
COMMENT
    ON COLUMN sys.td_menu.hidden IS '隐藏';
COMMENT
    ON COLUMN sys.td_menu.permission IS '权限';
COMMENT
    ON COLUMN sys.td_menu.create_by IS '创建者';
COMMENT
    ON COLUMN sys.td_menu.update_by IS '更新者';
COMMENT
    ON COLUMN sys.td_menu.create_time IS '创建日期';
COMMENT
    ON COLUMN sys.td_menu.update_time IS '更新时间';

-- sys.td_quartz_job
-- drop table if exists sys.td_quartz_job;
CREATE TABLE sys.td_quartz_job
(
    job_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bean_name           VARCHAR(255),
    cron_expression     VARCHAR(255),
    is_pause            BOOLEAN,
    job_name            VARCHAR(255),
    method_name         VARCHAR(255),
    params              VARCHAR(255),
    description         VARCHAR(255),
    person_in_charge    VARCHAR(100),
    email               VARCHAR(100),
    sub_task            VARCHAR(100),
    pause_after_failure BOOLEAN,
    create_by           VARCHAR(255),
    update_by           VARCHAR(255),
    create_time         TIMESTAMP,
    update_time         TIMESTAMP
);
CREATE INDEX idx_sys_quartz_job_is_pause ON sys.td_quartz_job (is_pause);
COMMENT
    ON TABLE sys.td_quartz_job IS '定时任务';
COMMENT
    ON COLUMN sys.td_quartz_job.job_id IS 'ID';
COMMENT
    ON COLUMN sys.td_quartz_job.bean_name IS 'Spring Bean名称';
COMMENT
    ON COLUMN sys.td_quartz_job.cron_expression IS 'cron 表达式';
COMMENT
    ON COLUMN sys.td_quartz_job.is_pause IS '状态：1暂停、0启用';
COMMENT
    ON COLUMN sys.td_quartz_job.job_name IS '任务名称';
COMMENT
    ON COLUMN sys.td_quartz_job.method_name IS '方法名称';
COMMENT
    ON COLUMN sys.td_quartz_job.params IS '参数';
COMMENT
    ON COLUMN sys.td_quartz_job.description IS '描述';
COMMENT
    ON COLUMN sys.td_quartz_job.person_in_charge IS '负责人';
COMMENT
    ON COLUMN sys.td_quartz_job.email IS '报警邮箱';
COMMENT
    ON COLUMN sys.td_quartz_job.sub_task IS '子任务ID';
COMMENT
    ON COLUMN sys.td_quartz_job.pause_after_failure IS '失败后暂停';
COMMENT
    ON COLUMN sys.td_quartz_job.create_by IS '创建者';
COMMENT
    ON COLUMN sys.td_quartz_job.update_by IS '更新者';
COMMENT
    ON COLUMN sys.td_quartz_job.create_time IS '创建日期';
COMMENT
    ON COLUMN sys.td_quartz_job.update_time IS '更新时间';

-- sys_role
-- drop table if exists sys.td_role;
CREATE TABLE sys.td_role
(
    role_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    level       INTEGER,
    description VARCHAR(255),
    data_scope  VARCHAR(255),
    create_by   VARCHAR(255),
    update_by   VARCHAR(255),
    create_time TIMESTAMP,
    update_time TIMESTAMP,
    UNIQUE (name)
);
CREATE INDEX idx_sys_role_level ON sys.td_role (level);
COMMENT
    ON TABLE sys.td_role IS '角色表';
COMMENT
    ON COLUMN sys.td_role.role_id IS 'ID';
COMMENT
    ON COLUMN sys.td_role.name IS '名称';
COMMENT
    ON COLUMN sys.td_role.level IS '角色级别';
COMMENT
    ON COLUMN sys.td_role.description IS '描述';
COMMENT
    ON COLUMN sys.td_role.data_scope IS '数据权限';
COMMENT
    ON COLUMN sys.td_role.create_by IS '创建者';
COMMENT
    ON COLUMN sys.td_role.update_by IS '更新者';
COMMENT
    ON COLUMN sys.td_role.create_time IS '创建日期';
COMMENT
    ON COLUMN sys.td_role.update_time IS '更新时间';

-- sys_roles_depts
-- drop table if exists sys.td_roles_depts;
CREATE TABLE sys.td_roles_depts
(
    role_id BIGINT NOT NULL,
    dept_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, dept_id)
);
CREATE INDEX idx_sys_roles_depts_role_id ON sys.td_roles_depts (role_id);
CREATE INDEX idx_sys_roles_depts_dept_id ON sys.td_roles_depts (dept_id);
COMMENT
    ON TABLE sys.td_roles_depts IS '角色部门关联';
COMMENT
    ON COLUMN sys.td_roles_depts.role_id IS '角色ID';
COMMENT
    ON COLUMN sys.td_roles_depts.dept_id IS '部门ID';

-- sys_roles_menus
-- drop table if exists sys.td_roles_menus;
CREATE TABLE sys.td_roles_menus
(
    menu_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (menu_id, role_id)
);
CREATE INDEX idx_sys_roles_menus_menu_id ON sys.td_roles_menus (menu_id);
CREATE INDEX idx_sys_roles_menus_role_id ON sys.td_roles_menus (role_id);
COMMENT
    ON TABLE sys.td_roles_menus IS '角色菜单关联';
COMMENT
    ON COLUMN sys.td_roles_menus.menu_id IS '菜单ID';
COMMENT
    ON COLUMN sys.td_roles_menus.role_id IS '角色ID';

-- sys.td_user
-- drop table if exists sys.td_user;
CREATE TABLE sys.td_user
(
    user_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_id        BIGINT,
    username       VARCHAR(180),
    nick_name      VARCHAR(255),
    gender         VARCHAR(2),
    phone          VARCHAR(255),
    email          VARCHAR(180),
    avatar_name    VARCHAR(255),
    avatar_path    VARCHAR(255),
    password       VARCHAR(255),
    is_admin       BOOLEAN DEFAULT FALSE,
    enabled        BOOLEAN,
    create_by      VARCHAR(255),
    update_by      VARCHAR(255),
    pwd_reset_time TIMESTAMP,
    create_time    TIMESTAMP,
    update_time    TIMESTAMP,
    UNIQUE (email),
    UNIQUE (username)
);
CREATE INDEX idx_sys_user_dept_id ON sys.td_user (dept_id);
CREATE INDEX idx_sys_user_enabled ON sys.td_user (enabled);
COMMENT
    ON TABLE sys.td_user IS '系统用户';
COMMENT
    ON COLUMN sys.td_user.user_id IS 'ID';
COMMENT
    ON COLUMN sys.td_user.dept_id IS '部门名称';
COMMENT
    ON COLUMN sys.td_user.username IS '用户名';
COMMENT
    ON COLUMN sys.td_user.nick_name IS '昵称';
COMMENT
    ON COLUMN sys.td_user.gender IS '性别';
COMMENT
    ON COLUMN sys.td_user.phone IS '手机号码';
COMMENT
    ON COLUMN sys.td_user.email IS '邮箱';
COMMENT
    ON COLUMN sys.td_user.avatar_name IS '头像地址';
COMMENT
    ON COLUMN sys.td_user.avatar_path IS '头像真实路径';
COMMENT
    ON COLUMN sys.td_user.password IS '密码';
COMMENT
    ON COLUMN sys.td_user.is_admin IS '是否为admin账号';
COMMENT
    ON COLUMN sys.td_user.enabled IS '状态：1启用、0禁用';
COMMENT
    ON COLUMN sys.td_user.create_by IS '创建者';
COMMENT
    ON COLUMN sys.td_user.update_by IS '更新者';
COMMENT
    ON COLUMN sys.td_user.pwd_reset_time IS '最后修改密码的日期';
COMMENT
    ON COLUMN sys.td_user.create_time IS '创建日期';
COMMENT
    ON COLUMN sys.td_user.update_time IS '更新时间';

-- sys.td_users_jobs
-- drop table if exists sys.td_users_jobs;
CREATE TABLE sys.td_users_jobs
(
    user_id BIGINT NOT NULL,
    job_id  BIGINT NOT NULL,
    PRIMARY KEY (user_id, job_id)
);
CREATE INDEX idx_sys_users_jobs_user_id ON sys.td_users_jobs (user_id);
CREATE INDEX idx_sys_users_jobs_job_id ON sys.td_users_jobs (job_id);
COMMENT
    ON TABLE sys.td_users_jobs IS '用户与岗位关联表';
COMMENT
    ON COLUMN sys.td_users_jobs.user_id IS '用户ID';
COMMENT
    ON COLUMN sys.td_users_jobs.job_id IS '岗位ID';

-- sys.td_users_roles
-- drop table if exists sys.td_users_roles;
CREATE TABLE sys.td_users_roles
(
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id)
);
CREATE INDEX idx_sys_users_roles_user_id ON sys.td_users_roles (user_id);
CREATE INDEX idx_sys_users_roles_role_id ON sys.td_users_roles (role_id);
COMMENT
    ON TABLE sys.td_users_roles IS '用户角色关联';
COMMENT
    ON COLUMN sys.td_users_roles.user_id IS '用户ID';
COMMENT
    ON COLUMN sys.td_users_roles.role_id IS '角色ID';

-- ========================
-- 插入初始数据
-- ========================

INSERT INTO sys.td_dept (dept_id, pid, sub_count, name, dept_sort, enabled, create_by, update_by, create_time,
                         update_time)
VALUES (1, NULL, 4, '重庆本部', 0, TRUE, 'admin', 'admin', '2019-03-25 09:11:25', '2020-06-08 12:08:42'),
       (101, 1, 5, '研发部', 0, TRUE, 'admin', 'admin', '2019-03-25 09:15:32', '2020-08-02 14:48:47'),
       (1001, 101, 0, '多式联运研发部', 0, TRUE, 'admin', 'admin', '2019-03-25 09:20:44', '2020-05-17 14:27:27'),
       (1002, 101, 0, '门户订舱研发部', 1, TRUE, 'admin', 'admin', '2019-03-25 09:20:44', '2020-05-17 14:27:27'),
       (1003, 101, 0, '园区仓储研发部', 2, TRUE, 'admin', 'admin', '2019-03-25 09:20:44', '2020-05-17 14:27:27'),
       (1004, 101, 0, '财务结算研发部', 3, TRUE, 'admin', 'admin', '2019-03-25 09:20:44', '2020-05-17 14:27:27'),
       (1005, 101, 0, 'UI研发部', 4, TRUE, 'admin', 'admin', '2019-03-25 09:20:44', '2020-05-17 14:27:27'),
       (102, 1, 0, '商务部', 1, TRUE, 'admin', 'admin', '2019-03-25 09:20:44', '2020-05-17 14:27:27'),
       (103, 1, 3, '综合部', 2, TRUE, 'admin', 'admin', '2019-03-25 09:52:18', '2020-06-08 11:59:21'),
       (3001, 103, 0, '人力资源部', 0, TRUE, 'admin', 'admin', '2019-03-25 09:52:18', '2020-06-08 11:59:21'),
       (3002, 103, 0, '财务部', 1, TRUE, 'admin', 'admin', '2019-03-25 09:52:18', '2020-06-08 11:59:21'),
       (3003, 103, 0, '销售部', 2, TRUE, 'admin', 'admin', '2019-03-25 09:52:18', '2020-06-08 11:59:21'),
       (104, 1, 0, '领导层', 3, TRUE, 'admin', 'admin', '2019-03-25 09:52:18', '2020-06-08 11:59:21'),
       (2, NULL, 0, '南宁分公司', 1, TRUE, 'admin', 'admin', '2019-03-25 09:12:33', '2020-06-08 12:08:47');

INSERT INTO sys.td_dict (dict_id, name, description, create_by, update_by, create_time, update_time)
VALUES (1, 'user_status', '用户状态', 'admin', NULL, '2019-10-27 20:31:36', NULL),
       (2, 'dept_status', '部门状态', 'admin', NULL, '2019-10-27 20:31:36', NULL),
       (3, 'job_status', '岗位状态', 'admin', NULL, '2019-10-27 20:31:36', NULL);

INSERT INTO sys.td_dict_detail (detail_id, dict_id, label, value, dict_sort, create_by, update_by, create_time,
                                update_time)
VALUES (1, 1, '激活', 'true', 1, 'admin', NULL, '2019-10-27 20:31:36', NULL),
       (2, 1, '禁用', 'false', 2, 'admin', NULL, '2019-10-27 20:31:36', NULL),
       (3, 2, '启用', 'true', 1, 'admin', NULL, '2019-10-27 20:31:36', NULL),
       (4, 2, '停用', 'false', 2, 'admin', NULL, '2019-10-27 20:31:36', NULL),
       (5, 3, '启用', 'true', 1, 'admin', NULL, '2019-10-27 20:31:36', NULL),
       (6, 3, '停用', 'false', 2, 'admin', NULL, '2019-10-27 20:31:36', NULL);

INSERT INTO sys.td_job (job_id, name, enabled, job_sort, create_by, update_by, create_time, update_time)
VALUES (1, '人事专员', TRUE, 0, NULL, NULL, '2019-03-29 14:52:28', NULL),
       (2, '产品经理', TRUE, 1, NULL, NULL, '2019-03-29 14:55:51', NULL),
       (3, '全栈开发', TRUE, 2, NULL, 'admin', '2019-03-31 13:39:30', '2020-05-05 11:33:43'),
       (4, '软件测试', TRUE, 3, NULL, 'admin', '2019-03-31 13:39:43', '2020-05-10 19:56:26');

INSERT INTO sys.td_menu (menu_id, pid, sub_count, type, title, name, component, menu_sort, icon, path, i_frame, cache,
                      hidden, permission, create_by, update_by, create_time, update_time)
VALUES (1, NULL, 7, 0, '系统管理', NULL, NULL, 1, 'system', 'system', FALSE, FALSE, FALSE, NULL, NULL, 'admin',
        '2018-12-18 15:11:29', '2025-01-14 15:48:18'),
       (2, 1, 3, 1, '用户管理', 'User', 'system/user/index', 2, 'peoples', 'user', FALSE, FALSE, FALSE, 'user:list',
        NULL, NULL, '2018-12-18 15:14:44', NULL),
       (3, 1, 3, 1, '角色管理', 'Role', 'system/role/index', 3, 'role', 'role', FALSE, FALSE, FALSE, 'roles:list', NULL,
        NULL, '2018-12-18 15:16:07', NULL),
       (5, 1, 3, 1, '菜单管理', 'Menu', 'system/menu/index', 5, 'menu', 'menu', FALSE, FALSE, FALSE, 'menu:list', NULL,
        NULL, '2018-12-18 15:17:28', NULL),
       (6, NULL, 5, 0, '系统监控', NULL, NULL, 10, 'monitor', 'monitor', FALSE, FALSE, FALSE, NULL, NULL, NULL,
        '2018-12-18 15:17:48', NULL),
       (7, 6, 0, 1, '操作日志', 'Log', 'monitor/log/index', 11, 'log', 'logs', FALSE, TRUE, FALSE, NULL, NULL, 'admin',
        '2018-12-18 15:18:26', '2020-06-06 13:11:57'),
       (9, 6, 0, 1, 'SQL监控', 'Sql', 'monitor/sql/index', 18, 'sqlMonitor', 'druid', FALSE, FALSE, FALSE, NULL, NULL,
        NULL, '2018-12-18 15:19:34', NULL),
       (10, NULL, 5, 0, '组件管理', NULL, NULL, 50, 'zujian', 'components', FALSE, FALSE, FALSE, NULL, NULL, NULL,
        '2018-12-19 13:38:16', NULL),
       (11, 10, 0, 1, '图标库', 'Icons', 'components/icons/index', 51, 'icon', 'icon', FALSE, FALSE, FALSE, NULL, NULL,
        NULL, '2018-12-19 13:38:49', NULL),
       (14, 36, 0, 1, '邮件工具', 'Email', 'tools/email/index', 35, 'email', 'email', FALSE, FALSE, FALSE, NULL, NULL,
        NULL, '2018-12-27 10:13:09', NULL),
       (15, 10, 0, 1, '富文本', 'Editor', 'components/Editor', 52, 'fwb', 'tinymce', FALSE, FALSE, FALSE, NULL, NULL,
        NULL, '2018-12-27 11:58:25', NULL),
       (18, 36, 3, 1, '存储管理', 'Storage', 'tools/storage/index', 34, 'qiniu', 'storage', FALSE, FALSE, FALSE,
        'storage:list', NULL, NULL, '2018-12-31 11:12:15', NULL),
       (19, 36, 0, 1, '支付宝工具', 'AliPay', 'tools/aliPay/index', 37, 'alipay', 'aliPay', FALSE, FALSE, FALSE, NULL,
        NULL, NULL, '2018-12-31 14:52:38', NULL),
       (21, NULL, 2, 0, '多级菜单', NULL, '', 900, 'menu', 'nested', FALSE, FALSE, FALSE, NULL, NULL, 'admin',
        '2019-01-04 16:22:03', '2020-06-21 17:27:35'),
       (22, 21, 2, 0, '二级菜单1', NULL, '', 999, 'menu', 'menu1', FALSE, FALSE, FALSE, NULL, NULL, 'admin',
        '2019-01-04 16:23:29', '2020-06-21 17:27:20'),
       (23, 21, 0, 1, '二级菜单2', NULL, 'nested/menu2/index', 999, 'menu', 'menu2', FALSE, FALSE, FALSE, NULL, NULL,
        NULL, '2019-01-04 16:23:57', NULL),
       (24, 22, 0, 1, '三级菜单1', 'Test', 'nested/menu1/menu1-1', 999, 'menu', 'menu1-1', FALSE, FALSE, FALSE, NULL,
        NULL, NULL, '2019-01-04 16:24:48', NULL),
       (27, 22, 0, 1, '三级菜单2', NULL, 'nested/menu1/menu1-2', 999, 'menu', 'menu1-2', FALSE, FALSE, FALSE, NULL,
        NULL, NULL, '2019-01-07 17:27:32', NULL),
       (28, 1, 3, 1, '任务调度', 'Timing', 'system/timing/index', 999, 'timing', 'timing', FALSE, FALSE, FALSE,
        'timing:list', NULL, NULL, '2019-01-07 20:34:40', NULL),
       (30, 36, 0, 1, '代码生成', 'GeneratorIndex', 'generator/index', 32, 'dev', 'generator', FALSE, TRUE, FALSE, NULL,
        NULL, NULL, '2019-01-11 15:45:55', NULL),
       (32, 6, 0, 1, '异常日志', 'ErrorLog', 'monitor/log/errorLog', 12, 'error', 'errorLog', FALSE, FALSE, FALSE, NULL,
        NULL, NULL, '2019-01-13 13:49:03', NULL),
       (33, 10, 0, 1, 'Markdown', 'Markdown', 'components/MarkDown', 53, 'markdown', 'markdown', FALSE, FALSE, FALSE,
        NULL, NULL, NULL, '2019-03-08 13:46:44', NULL),
       (34, 10, 0, 1, 'Yaml编辑器', 'YamlEdit', 'components/YamlEdit', 54, 'dev', 'yaml', FALSE, FALSE, FALSE, NULL,
        NULL, NULL, '2019-03-08 15:49:40', NULL),
       (35, 1, 3, 1, '部门管理', 'Dept', 'system/dept/index', 6, 'dept', 'dept', FALSE, FALSE, FALSE, 'dept:list', NULL,
        NULL, '2019-03-25 09:46:00', NULL),
       (36, NULL, 6, 0, '系统工具', NULL, '', 30, 'sys-tools', 'sys-tools', FALSE, FALSE, FALSE, NULL, NULL, NULL,
        '2019-03-29 10:57:35', NULL),
       (37, 1, 3, 1, '岗位管理', 'Job', 'system/job/index', 7, 'Steve-Jobs', 'job', FALSE, FALSE, FALSE, 'job:list',
        NULL, NULL, '2019-03-29 13:51:18', NULL),
       (39, 1, 3, 1, '字典管理', 'Dict', 'system/dict/index', 8, 'dictionary', 'dict', FALSE, FALSE, FALSE, 'dict:list',
        NULL, NULL, '2019-04-10 11:49:04', NULL),
       (41, 6, 0, 1, '在线用户', 'OnlineUser', 'monitor/online/index', 10, 'Steve-Jobs', 'online', FALSE, FALSE, FALSE,
        NULL, NULL, NULL, '2019-10-26 22:08:43', NULL),
       (44, 2, 0, 2, '用户新增', NULL, '', 2, '', '', FALSE, FALSE, FALSE, 'user:add', NULL, NULL,
        '2019-10-29 10:59:46', NULL),
       (45, 2, 0, 2, '用户编辑', NULL, '', 3, '', '', FALSE, FALSE, FALSE, 'user:edit', NULL, NULL,
        '2019-10-29 11:00:08', NULL),
       (46, 2, 0, 2, '用户删除', NULL, '', 4, '', '', FALSE, FALSE, FALSE, 'user:del', NULL, NULL,
        '2019-10-29 11:00:23', NULL),
       (48, 3, 0, 2, '角色创建', NULL, '', 2, '', '', FALSE, FALSE, FALSE, 'roles:add', NULL, NULL,
        '2019-10-29 12:45:34', NULL),
       (49, 3, 0, 2, '角色修改', NULL, '', 3, '', '', FALSE, FALSE, FALSE, 'roles:edit', NULL, NULL,
        '2019-10-29 12:46:16', NULL),
       (50, 3, 0, 2, '角色删除', NULL, '', 4, '', '', FALSE, FALSE, FALSE, 'roles:del', NULL, NULL,
        '2019-10-29 12:46:51', NULL),
       (52, 5, 0, 2, '菜单新增', NULL, '', 2, '', '', FALSE, FALSE, FALSE, 'menu:add', NULL, NULL,
        '2019-10-29 12:55:07', NULL),
       (53, 5, 0, 2, '菜单编辑', NULL, '', 3, '', '', FALSE, FALSE, FALSE, 'menu:edit', NULL, NULL,
        '2019-10-29 12:55:40', NULL),
       (54, 5, 0, 2, '菜单删除', NULL, '', 4, '', '', FALSE, FALSE, FALSE, 'menu:del', NULL, NULL,
        '2019-10-29 12:56:00', NULL),
       (56, 35, 0, 2, '部门新增', NULL, '', 2, '', '', FALSE, FALSE, FALSE, 'dept:add', NULL, NULL,
        '2019-10-29 12:57:09', NULL),
       (57, 35, 0, 2, '部门编辑', NULL, '', 3, '', '', FALSE, FALSE, FALSE, 'dept:edit', NULL, NULL,
        '2019-10-29 12:57:27', NULL),
       (58, 35, 0, 2, '部门删除', NULL, '', 4, '', '', FALSE, FALSE, FALSE, 'dept:del', NULL, NULL,
        '2019-10-29 12:57:41', NULL),
       (60, 37, 0, 2, '岗位新增', NULL, '', 2, '', '', FALSE, FALSE, FALSE, 'job:add', NULL, NULL,
        '2019-10-29 12:58:27', NULL),
       (61, 37, 0, 2, '岗位编辑', NULL, '', 3, '', '', FALSE, FALSE, FALSE, 'job:edit', NULL, NULL,
        '2019-10-29 12:58:45', NULL),
       (62, 37, 0, 2, '岗位删除', NULL, '', 4, '', '', FALSE, FALSE, FALSE, 'job:del', NULL, NULL,
        '2019-10-29 12:59:04', NULL),
       (64, 39, 0, 2, '字典新增', NULL, '', 2, '', '', FALSE, FALSE, FALSE, 'dict:add', NULL, NULL,
        '2019-10-29 13:00:17', NULL),
       (65, 39, 0, 2, '字典编辑', NULL, '', 3, '', '', FALSE, FALSE, FALSE, 'dict:edit', NULL, NULL,
        '2019-10-29 13:00:42', NULL),
       (66, 39, 0, 2, '字典删除', NULL, '', 4, '', '', FALSE, FALSE, FALSE, 'dict:del', NULL, NULL,
        '2019-10-29 13:00:59', NULL),
       (73, 28, 0, 2, '任务新增', NULL, '', 2, '', '', FALSE, FALSE, FALSE, 'timing:add', NULL, NULL,
        '2019-10-29 13:07:28', NULL),
       (74, 28, 0, 2, '任务编辑', NULL, '', 3, '', '', FALSE, FALSE, FALSE, 'timing:edit', NULL, NULL,
        '2019-10-29 13:07:41', NULL),
       (75, 28, 0, 2, '任务删除', NULL, '', 4, '', '', FALSE, FALSE, FALSE, 'timing:del', NULL, NULL,
        '2019-10-29 13:07:54', NULL),
       (77, 18, 0, 2, '上传文件', NULL, '', 2, '', '', FALSE, FALSE, FALSE, 'storage:add', NULL, NULL,
        '2019-10-29 13:09:09', NULL),
       (78, 18, 0, 2, '文件编辑', NULL, '', 3, '', '', FALSE, FALSE, FALSE, 'storage:edit', NULL, NULL,
        '2019-10-29 13:09:22', NULL),
       (79, 18, 0, 2, '文件删除', NULL, '', 4, '', '', FALSE, FALSE, FALSE, 'storage:del', NULL, NULL,
        '2019-10-29 13:09:34', NULL),
       (80, 6, 0, 1, '服务监控', 'ServerMonitor', 'monitor/server/index', 14, 'codeConsole', 'server', FALSE, FALSE,
        FALSE, 'monitor:list', NULL, 'admin', '2019-11-07 13:06:39', '2020-05-04 18:20:50'),
       (82, 36, 0, 1, '生成配置', 'GeneratorConfig', 'generator/config', 33, 'dev', 'generator/config/:tableName',
        FALSE, TRUE, TRUE, '', NULL, NULL, '2019-11-17 20:08:56', NULL),
       (83, 10, 0, 1, '图表库', 'Echarts', 'components/Echarts', 50, 'chart', 'echarts', FALSE, TRUE, FALSE, '', NULL,
        NULL, '2019-11-21 09:04:32', NULL),
       (90, NULL, 5, 1, '运维管理', 'Mnt', '', 20, 'mnt', 'mnt', FALSE, FALSE, FALSE, NULL, NULL, NULL,
        '2019-11-09 10:31:08', NULL),
       (92, 90, 3, 1, '服务器', 'ServerDeploy', 'maint/server/index', 22, 'server', 'maint/serverDeploy', FALSE, FALSE,
        FALSE, 'serverDeploy:list', NULL, NULL, '2019-11-10 10:29:25', NULL),
       (93, 90, 3, 1, '应用管理', 'App', 'maint/app/index', 23, 'app', 'maint/app', FALSE, FALSE, FALSE, 'app:list',
        NULL, NULL, '2019-11-10 11:05:16', NULL),
       (94, 90, 3, 1, '部署管理', 'Deploy', 'maint/deploy/index', 24, 'deploy', 'maint/deploy', FALSE, FALSE, FALSE,
        'deploy:list', NULL, NULL, '2019-11-10 15:56:55', NULL),
       (97, 90, 1, 1, '部署备份', 'DeployHistory', 'maint/deployHistory/index', 25, 'backup', 'maint/deployHistory',
        FALSE, FALSE, FALSE, 'deployHistory:list', NULL, NULL, '2019-11-10 16:49:44', NULL),
       (98, 90, 3, 1, '数据库管理', 'Database', 'maint/database/index', 26, 'database', 'maint/database', FALSE, FALSE,
        FALSE, 'database:list', NULL, NULL, '2019-11-10 20:40:04', NULL),
       (102, 97, 0, 2, '删除', NULL, '', 999, '', '', FALSE, FALSE, FALSE, 'deployHistory:del', NULL, NULL,
        '2019-11-17 09:32:48', NULL),
       (103, 92, 0, 2, '服务器新增', NULL, '', 999, '', '', FALSE, FALSE, FALSE, 'serverDeploy:add', NULL, NULL,
        '2019-11-17 11:08:33', NULL),
       (104, 92, 0, 2, '服务器编辑', NULL, '', 999, '', '', FALSE, FALSE, FALSE, 'serverDeploy:edit', NULL, NULL,
        '2019-11-17 11:08:57', NULL),
       (105, 92, 0, 2, '服务器删除', NULL, '', 999, '', '', FALSE, FALSE, FALSE, 'serverDeploy:del', NULL, NULL,
        '2019-11-17 11:09:15', NULL),
       (106, 93, 0, 2, '应用新增', NULL, '', 999, '', '', FALSE, FALSE, FALSE, 'app:add', NULL, NULL,
        '2019-11-17 11:10:03', NULL),
       (107, 93, 0, 2, '应用编辑', NULL, '', 999, '', '', FALSE, FALSE, FALSE, 'app:edit', NULL, NULL,
        '2019-11-17 11:10:28', NULL),
       (108, 93, 0, 2, '应用删除', NULL, '', 999, '', '', FALSE, FALSE, FALSE, 'app:del', NULL, NULL,
        '2019-11-17 11:10:55', NULL),
       (109, 94, 0, 2, '部署新增', NULL, '', 999, '', '', FALSE, FALSE, FALSE, 'deploy:add', NULL, NULL,
        '2019-11-17 11:11:22', NULL),
       (110, 94, 0, 2, '部署编辑', NULL, '', 999, '', '', FALSE, FALSE, FALSE, 'deploy:edit', NULL, NULL,
        '2019-11-17 11:11:41', NULL),
       (111, 94, 0, 2, '部署删除', NULL, '', 999, '', '', FALSE, FALSE, FALSE, 'deploy:del', NULL, NULL,
        '2019-11-17 11:12:01', NULL),
       (116, 36, 0, 1, '生成预览', 'Preview', 'generator/preview', 999, 'java', 'generator/preview/:tableName', FALSE,
        TRUE, TRUE, NULL, NULL, NULL, '2019-11-26 14:54:36', NULL);

INSERT INTO sys.td_quartz_job (job_id, bean_name, cron_expression, is_pause, job_name, method_name, params, description,
                            person_in_charge, email, sub_task, pause_after_failure, create_by, update_by, create_time,
                            update_time)
VALUES (2, 'testTask', '0/5 * * * * ?', TRUE, '测试1', 'run1', 'test', '带参测试，多参使用json', '测试', NULL, NULL,
        NULL, NULL, 'admin', '2019-08-22 14:08:29', '2020-05-24 13:58:33'),
       (3, 'testTask', '0/5 * * * * ?', TRUE, '测试', 'run', '', '不带参测试', 'Zheng Jie', '', '6', TRUE, NULL,
        'admin', '2019-09-26 16:44:39', '2020-05-24 14:48:12'),
       (5, 'Test', '0/5 * * * * ?', TRUE, '任务告警测试', 'run', NULL, '测试', 'test', '', NULL, TRUE, 'admin', 'admin',
        '2020-05-05 20:32:41', '2020-05-05 20:36:13'),
       (6, 'testTask', '0/5 * * * * ?', TRUE, '测试3', 'run2', NULL, '测试3', 'Zheng Jie', '', NULL, TRUE, 'admin',
        'admin', '2020-05-05 20:35:41', '2020-05-05 20:36:07');

INSERT INTO sys.td_role (role_id, name, level, description, data_scope, create_by, update_by, create_time, update_time)
VALUES (1, '管理员', 1, '-', '全部', NULL, 'admin', '2018-11-23 11:04:37', '2025-01-21 14:53:13'),
       (2, '普通用户', 2, '-', '本级', NULL, 'admin', '2018-11-23 13:09:06', '2020-09-05 10:45:12');

INSERT INTO sys.td_roles_menus (menu_id, role_id)
VALUES (1, 1),
       (1, 2),
       (2, 1),
       (2, 2),
       (3, 1),
       (5, 1),
       (6, 1),
       (6, 2),
       (7, 1),
       (7, 2),
       (9, 1),
       (9, 2),
       (10, 1),
       (10, 2),
       (11, 1),
       (11, 2),
       (14, 1),
       (14, 2),
       (15, 1),
       (15, 2),
       (18, 1),
       (19, 1),
       (19, 2),
       (21, 1),
       (21, 2),
       (22, 1),
       (22, 2),
       (23, 1),
       (23, 2),
       (24, 1),
       (24, 2),
       (27, 1),
       (27, 2),
       (28, 1),
       (30, 1),
       (30, 2),
       (32, 1),
       (32, 2),
       (33, 1),
       (33, 2),
       (34, 1),
       (34, 2),
       (35, 1),
       (36, 1),
       (36, 2),
       (37, 1),
       (39, 1),
       (41, 1),
       (44, 1),
       (45, 1),
       (46, 1),
       (48, 1),
       (49, 1),
       (50, 1),
       (52, 1),
       (53, 1),
       (54, 1),
       (56, 1),
       (57, 1),
       (58, 1),
       (60, 1),
       (61, 1),
       (62, 1),
       (64, 1),
       (65, 1),
       (66, 1),
       (73, 1),
       (74, 1),
       (75, 1),
       (77, 1),
       (78, 1),
       (79, 1),
       (80, 1),
       (80, 2),
       (82, 1),
       (82, 2),
       (83, 1),
       (83, 2),
       (90, 1),
       (92, 1),
       (93, 1),
       (94, 1),
       (97, 1),
       (98, 1),
       (102, 1),
       (103, 1),
       (104, 1),
       (105, 1),
       (106, 1),
       (107, 1),
       (108, 1),
       (109, 1),
       (110, 1),
       (111, 1),
       (116, 1),
       (116, 2);

INSERT INTO sys.td_user (user_id, dept_id, username, nick_name, gender, phone, email, avatar_name, avatar_path, password,
                         is_admin, enabled, create_by, update_by, pwd_reset_time, create_time, update_time)
VALUES (1, 1, 'admin', '管理员', '男', '18888888888', '201507802@qq.com', NULL,NULL,
        '$2a$10$Egp1/gvFlt7zhlXVfEFw4OfWQCGPw0ClmMcc6FjTnvXNRVf9zdMRa', TRUE, TRUE, NULL, 'admin',
        '2020-05-03 16:38:31', '2018-08-23 09:11:56', '2025-01-22 10:26:42'),
       (2, 2, 'test', '测试', '男', '19999999999', '231@qq.com', NULL, NULL,
        '$2a$10$4XcyudOYTSz6fue6KFNMHeUQnCX5jbBQypLEnGk1PmekXt5c95JcK', FALSE, TRUE, 'admin', 'admin', NULL,
        '2020-05-05 11:15:49', '2025-01-21 14:53:04');

INSERT INTO sys.td_users_jobs (user_id, job_id)
VALUES (1, 1),
       (2, 2);

INSERT INTO sys.td_users_roles (user_id, role_id)
VALUES (1, 1),
       (2, 2);

COMMIT;